ktor:
  application:
    modules:
      - team.microchad.ApplicationKt.module
  deployment:
    port: 8080
db:
  url: 85.193.80.124
  port: 5432
  name: mmbot
  user: jira
  password: password

bot:
  host: $BOT_HOST
  auth:
    username: $BOT_USERNAME
    password: $BOT_PASSWORD
    token: $MM_TOKEN
