ktor:
  application:
    modules:
      - team.microchad.ApplicationKt.module
  deployment:
    port: 8080
bot:
  host: $BOT_HOST
  auth:
    username: $BOT_USERNAME
    password: $BOT_PASSWORD
    token: $MM_TOKEN
